name: test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DevOpsDir: ""
  ShouldPublish:

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Initializing the test!"
        shell: bash

  Start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "READ"
        shell: bash
      - run: cat $GITHUB_WORKSPACE/testFile
        shell: bash




        