name: test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing
        run: echo "Starting the test!"
        shell: bash