name: test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DevOpsDir: "devops-dir"
  ShouldPublish:

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Initializing the test!"
        shell: bash
      - run: echo "READ Workspace"
        shell: bash
      - run: ls -la $GITHUB_WORKSPACE
        shell: bash
      - run: cat $GITHUB_WORKSPACE/testFile
        shell: bash   
      - run: echo "$DevOpsDir"
        shell: bash
        env:
          DevOpsDir: "devops-dir2"
      - run: echo "$DevOpsDir"
        shell: bash