name: test1

on:
  push:
    - main
  
  workflow_dispatch:

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:

  build-and-test:
    name: build and test on push to main

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkou@2