name: test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DevOpsDir: ""
  # ShouldPublish: false 
  ## izbacen jer koristimo Publish step drugacije
  ## env u okviru joba ne moze da pregazi globalni env van tog joba, shouldPublish env de se mrda iz init-devops tamo gde se koristi, i tamo se radi provera if job name ends with -rc

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init-SCM:
    runs-on: windows-latest
    steps:
      - run: echo "Init-SCM"
        shell: pwsh

  # Init-DevOps:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: echo "Initializing the test!"
  #       shell: bash
  #     - run: echo "READ Workspace"
  #       shell: bash
  #     - run: ls -la $GITHUB_WORKSPACE
  #       shell: bash
  #     - run: cat $GITHUB_WORKSPACE/testFile
  #       shell: bash

  Versions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\windows.ps1
        shell: pwsh
      # - run: echo $env:ShouldPublish
      #   shell: pwsh

  Publish:
    runs-on: windows-latest
    if: endsWith(github.event.repository.name '-rc')
    steps:
      - run: echo "test working"
        shell: pwsh
      - run: echo $env:GITHUB_ACTION_REPOSITORY
        shell: pwsh
