name: stoxx-datamanager-ci

on:
  push:
    branches:
      - main #pull request here
  workflow_dispatch:

env:
  DevOpsDir: ""
  # ShouldPublish: false 
  ## izbacen jer koristimo Publish step drugacije
  ## env u okviru joba ne moze da pregazi globalni env van tog joba, shouldPublish env de se mrda iz init-devops tamo gde se koristi, i tamo se radi provera if job name ends with -rc

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init-SCM:
    runs-on: windows-latest
    steps:
      - run: echo "Init-SCM"
        shell: pwsh

  Init-DevOps:
    needs: Init-SCM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Initializing the test!"
        shell: pwsh
      - run: echo "READ Workspace"
        shell: pwsh
      - run: ls $env:GITHUB_WORKSPACE
        shell: pwsh
      - run: cat $GITHUB_WORKSPACE/testFile
        shell: pwsh


  Versions:
    needs: Init-DevOps
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\windows.ps1 #change path to where git repo was cloned
        shell: pwsh

#   Restore:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: .\restore.ps1
#         shell: pwsh

#   Build:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: .\build.ps1
#         shell: pwsh

#  Test:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: .\test.ps1
#         shell: pwsh

  Publish:
    needs: Versions
    runs-on: windows-latest
    if: endsWith(github.event.repository.name, '-testing123')
    steps:
      - run: echo "test working" #add publish step here
        shell: pwsh

#   Finalize:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: .\test.ps1
#         shell: pwsh




# Post - u jenkinsu je nameste post always, sto znaci da nema condition.
# zasto onda ne bi bio samo jos jedan step, koji ide na kraju?

# Post - ovde stoji currentBuild.result = success ili fail u zavisnosti od post-a, 
# samim time nema potrebe da stoji u finalize stepu; 
# takodje, nigde se ne okida echo za taj result






