name: test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DevOpsDir: ""
  ShouldPublish:

#concurrency:
  #group: test-${{ github.head_ref }}

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing
        uses: actions/checkout@2

  Start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting the test!"
        shell: bash

      - run: echo "READ"
        shell: bash



        